apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: todo-list-preview
  namespace: argocd
spec:
  generators:
  - pullRequest:
      github:
        owner: wayn3r
        repo: todo-list
        tokenRef:
          secretName: github-token
          key: token
        labels:
        - preview
      requeueAfterSeconds: 60
  template:
    metadata:
      name: todo-list-{{branch_slug}}-{{number}}
      namespace: argocd
    spec:
      project: todo-list-previews
      source:
        repoURL: 'https://github.com/wayn3r/todo-list-argocd'
        path: 'todo-list-previews'
        targetRevision: HEAD
        kustomize:
          nameSuffix: "{{branch_slug}}"
          commonLabels:
            app.kubernetes.io/instance: '{{branch_slug}}-{{number}}'
          images:
          - wayn3r/todo-list-preview:{{head_sha}}
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: preview-todo-list-{{branch_slug}}-{{number}}
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
          - CreateNamespace=true