apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: wayn3r/todo-list:1d535309e883102d27bb88952d62a9e8132b5df0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      restartPolicy: Always