apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: wayn3r/todo-list:8cd3cdb99ed8c726a8af2a45574414ad0126a6d0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      restartPolicy: Always