apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-list
  labels:
    app: todo-list
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-list
  template:
    metadata:
      labels:
        app: todo-list
    spec:
      containers:
      - name: todo-list
        image: wayn3r/todo-list:db042a4afc7bc6b865fa82e21f9f5bb42c0807ac
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      restartPolicy: Always